services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Answear\LuigisBoxBundle\:
        resource: '../../../../src/LuigisBoxBundle/{Service,Factory}'

    Answear\LuigisBoxBundle\Service\ConfigProvider: ~

    Answear\LuigisBoxBundle\Service\RequestInterface:
        class: Answear\LuigisBoxBundle\Service\Request

    Answear\LuigisBoxBundle\Service\SearchRequestInterface:
        class: Answear\LuigisBoxBundle\Service\SearchRequest

